
jobs:
  - job: testingDownloadPipelineArtifact
    displayName: 'testing pipelines'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: DownloadPipelineArtifact@1
        displayName: 'Download server artifact files'
        inputs:
          buildType: 'specific'
          project: 'test'
          pipeline: 'rusher.pipeline_DL'
          artifactName: 'test-pipe'
          buildVersionToDownload: 'latest'
          #buildId: 5
          #buildVersionToDownload: 'specific'
          downloadPath: $(System.DefaultWorkingDirectory)
