
jobs:
  - job: testingDownloadPipelineArtifact
    displayName: 'retrieving  pipelines'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: DownloadPipelineArtifact@1
        displayName: 'Download server artifact files'
        inputs:
          buildType: 'specific'
          project: 'rusher.pipeline_DL'
#          pipeline: 'rusher.pipeline_DL'
          artifactName: 'test-pipe'
          buildVersionToDownload: 'latest'
          definition: '1'
          downloadPath: $(System.DefaultWorkingDirectory)
#          buildId: 9
#          buildVersionToDownload: 'specific'
