
jobs:
  - job: testingDownloadPipelineArtifact
    displayName: 'retrieving  pipelines'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: DownloadPipelineArtifact@1
        displayName: 'Download server artifact files'
        inputs:
          buildType: 'specific'
          project: 'f36b9048-dabc-4752-8626-cc67cd5a2a4f'
          pipeline: 'rusher.pipeline_DL'
          artifactName: 'test-pipe'
          buildVersionToDownload: 'latest'
          buildPipelineDefinition: '1'
          downloadPath: $(System.DefaultWorkingDirectory)
          #buildId: 9
          #buildVersionToDownload: 'specific'
